name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.100-rc.1.25451.107"

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build --no-restore --configuration Release ./src

      - name: Tests
        run: dotnet test --no-build --configuration Release ./src

      - name: Publish artifact
        run: dotnet publish --no-build ./src/BugStore.Api/BugStore.Api.csproj --configuration Release --output publish

      - name: Zip published artifact
        run: cd publish && zip -r ../published-app.zip . && cd ..
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: balta-desafio-halloween-2025
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './published-app.zip'